language: node_js
node_js:
  - "12"
addons:
  chrome: stable
install: skip
script:
  - cd clr-prototype-angular
  - yarn
  - yarn lint
  - yarn test
  - yarn build
  - cd ../clr-prototype-react
  - npm
  - npm run test
  - npm run build
  - cd ../
cache:
  yarn: true
