language: node_js
node_js:
  - "12"
addons:
  chrome: stable
install:
  - ls -ltra
  - yarn
  - yarn lint
  - yarn test
  - yarn build

cache:
  yarn: true
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - cd clr-prototype-angular
