language: node_js
node_js:
  - "12"
addons:
  chrome: stable
install:
  - cd clr-prototype-angular && yarn
  - cd clr-prototype-angular && yarn lint
  - cd clr-prototype-angular && yarn test
  - cd clr-prototype-angular && yarn build

cache:
  yarn: true
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
