language: node_js
node_js:
  - "12"
addons:
  chrome: stable
install: skip
script:
  - cd clr-prototype-angular
  - yarn
  - yarn lint
  - yarn test
  - yarn build
  - cd ../clr-prototype-react
  - npm i
  - npm run test
  - npm run build
  - cd ../
deploy:
  provider: firebase
  token: CChglQyykeN1bz1fRenjxRNxaPSmmiD3D65vBCT3gxHlvHsO+j2A7qgW/pNEtjddq8EgcXdkUuEq3152mAX/TXmvdYWk+i8fAFdBdns/K39X1PN6TZTyvKUIGjXL1dBswNqtKAPFwztsIuEFDTy4J4GTOJyUaM8d5GPtUlOaqnJ/R+X8YLcS0wK0kjauDiKxq1TZfPIsDKhNKOuJ7RFeaJ1uMxcxBNkYAanJGYQiugtkUBrxpi7ukKZRuZkubvOZrtAhjN+/p8zOI/HR3KQbHRdyG0FBDJeQw06CgNWezhTI9JuIDEd+B+ASfZzFmfWtGT1LWjRUr31P+oSiYo9xbKoUrhv4mG46hIf4SuZP40QR3DXwIRG24Tq+SHoTSB+xQEMtjRiOupAH77++iMWrVRn1Auja2wmTelDOmSo0rZr7yQnfRtXWloU9re+npPY7fUVVOgoIW1bXdIwi9sPYGWpMJvtkyPOO74nf0qVfUSOaWkPbT8Ml1RKh3Phv5Y6S40w84i1ZjSlYpuWS7rL2HjaCLL+YiNdczlKLfFlE697sW0nnQ0LEQkZW8AJESA0xJy27IYJ5at3D+woO4mqwPKF0S6x4zTAeS2UHRzyPeVPh5ODXVKnZbjw0N7i91stF1RaM+8wTYKM38MYo4mTgb4+vMa3E+P3s17ObMRdf5xo=
  project: clr-prototype
cache:
  yarn: true
