steps:
  # REACT
  - name: "gcr.io/cloud-builders/npm:node-10.10.0"
    args: ["install"]
    dir: "clr-prototype-react"
    timeout: 600s

  # Test
  - name: "gcr.io/cloud-builders/npm:node-10.10.0"
    args: ["run", "test:no-watch"]
    dir: "clr-prototype-react"
    timeout: 600s

  # Build
  - name: "gcr.io/cloud-builders/npm:node-10.10.0"
    args: ["run", "build"]
    dir: "clr-prototype-react"
    timeout: 600s

  # ANGULAR

  # Install
  - name: "gcr.io/cloud-builders/npm:node-10.10.0"
    args: ["install"]
    dir: "clr-prototype-angular"
    timeout: 600s

  # Test
  - name: "gcr.io/cloud-builders/npm:node-10.10.0"
    args: ["run", "test:no-watch"]
    dir: "clr-prototype-angular"
    timeout: 600s

  # Build
  - name: "gcr.io/cloud-builders/npm:node-10.10.0"
    args: ["run", "build", "--prod"]
    dir: "clr-prototype-angular"
    timeout: 600s

  # DEPLOY

  - name: "gcr.io/$PROJECT_ID/firebase"
    args: ["deploy", "--only", "hosting"]
    timeout: 600s
